project: 
  type: website
  output-dir: "." 

website:
  title: "Alivia R. Cochran"
  navbar:
    background: "black"
    pinned: true
    search: false
    left:
      - text: ''
        href: ''
    right:
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: resume-example.pdf
            
  # page-footer: 
  #   center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Alivia R. Cochran, 2025"

format:
  html:
    theme: cyborg
      # light: flatly # flatly sandstone yeti united litera journal
      # dark: darkly #  darkly cyborg slate solra superhero
    mainfont: Arial # system-ui; Agbalumo; sans-serif; monospace
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
fontsize: 16pt

